version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
#    allow:
#      - dependency-name: "org.springframework.boot"

    groups:
      # Group all gradle security updates
      gradle-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # Group all github-action updates
      github-actions:
        applies-to: version-updates
        patterns: [ "*" ]
    open-pull-requests-limit: 20
