version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "aleyipsoftwire"
    ignore: [ "uk.gov.dluhc*" ]
    groups:
      # Group all gradle security updates
      gradle-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      # Group all kotlin plugin updates
      kotlin-plugins:
        patterns:
          - "jvm"
          - "kapt"
          - "plugin.spring"
          - "plugin.jpa"
          - "plugin.allopen"
      # Group all direct version updates, except for Spring Boot
      gradle-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
        dependency-type: direct
        ignore:
          - "org.springframework.boot"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # Group all github-action updates
      github-actions:
        applies-to: version-updates
        patterns: [ "*" ]
